--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/OguzhanUmutlu/ComplexCrates
build-by-default: true
branches:
- main
projects:
  ComplexCrates:
    path: ""
    libs:
      - src: dktapps-pm-pl/pmforms/pmforms
        version: ^1.0.0
      - src: muqsit\invmenu\invmenu
        version: ^4.1
...
