---
form-enabled: true

# Language of the plugin:
# en_US: https://github.com/OguzhanUmutlu
# tr_TR: https://github.com/OguzhanUmutlu
# zh_CN: https://github.com/Endermanbugzjfc
# zh_TW: https://github.com/Endermanbugzjfc
# rus_RUS: https://github.com/kostamax27
language: en_US

# Options: yaml, json, properties
data-type: yaml

# Can more than one player open same crate?
crate-access: false

crate-command:
  name: "crate"
  description: "Manage crates"
  aliases:
    - "crates"
...
